### ISSUE TITLE
Add support to restart Jenkins when all jobs are done.

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-zh/jenkins-cli#131]
**Is your feature request related to a problem? Please describe.**
Done.

**Describe the solution you'd like**
Restart Jenkins when the plugin installation jobs are done.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by LinuxSuRen** [comment]
An alternative solution can be using post-hook. We provide a config like below:

```
postHooks:
- path: plugin.upload
  cmd: jcli center watch --util-install-complete
- path: plugin.upload
  cmd: jcli restart -b
```

So, once we execute command `jcli plugin upload` successfully, then the post-hook will be executed.

This solution requires #141
