### ISSUE TITLE
Hook comand shouldn't always executes even there's error exists

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-zh/jenkins-cli#159]
**Describe the bug**
Part of my config is below.
```
postHooks:
- path: plugin.upload
  cmd: jcli center watch --util-install-complete
- path: plugin.upload
  cmd: jcli restart -b
```
The command should stop if one of the preHooks is failed.

**To Reproduce**
1. Add the sample which I given into you config file
2. Execute command `jcli upload` under a plugin project source directory
4. See the result

**Expected behavior**
The command should not be executed once if there's some thing wrong.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: dev-v0.0.19

**Additional context**
None.
